require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChallengersController do

  # This should return the minimal set of attributes required to create a valid
  # Challenger. As you add validations to Challenger, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChallengersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all challengers as @challengers" do
      challenger = Challenger.create! valid_attributes
      get :index, {}, valid_session
      assigns(:challengers).should eq([challenger])
    end
  end

  describe "GET show" do
    it "assigns the requested challenger as @challenger" do
      challenger = Challenger.create! valid_attributes
      get :show, {:id => challenger.to_param}, valid_session
      assigns(:challenger).should eq(challenger)
    end
  end

  describe "GET new" do
    it "assigns a new challenger as @challenger" do
      get :new, {}, valid_session
      assigns(:challenger).should be_a_new(Challenger)
    end
  end

  describe "GET edit" do
    it "assigns the requested challenger as @challenger" do
      challenger = Challenger.create! valid_attributes
      get :edit, {:id => challenger.to_param}, valid_session
      assigns(:challenger).should eq(challenger)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Challenger" do
        expect {
          post :create, {:challenger => valid_attributes}, valid_session
        }.to change(Challenger, :count).by(1)
      end

      it "assigns a newly created challenger as @challenger" do
        post :create, {:challenger => valid_attributes}, valid_session
        assigns(:challenger).should be_a(Challenger)
        assigns(:challenger).should be_persisted
      end

      it "redirects to the created challenger" do
        post :create, {:challenger => valid_attributes}, valid_session
        response.should redirect_to(Challenger.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved challenger as @challenger" do
        # Trigger the behavior that occurs when invalid params are submitted
        Challenger.any_instance.stub(:save).and_return(false)
        post :create, {:challenger => {}}, valid_session
        assigns(:challenger).should be_a_new(Challenger)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Challenger.any_instance.stub(:save).and_return(false)
        post :create, {:challenger => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested challenger" do
        challenger = Challenger.create! valid_attributes
        # Assuming there are no other challengers in the database, this
        # specifies that the Challenger created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Challenger.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => challenger.to_param, :challenger => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested challenger as @challenger" do
        challenger = Challenger.create! valid_attributes
        put :update, {:id => challenger.to_param, :challenger => valid_attributes}, valid_session
        assigns(:challenger).should eq(challenger)
      end

      it "redirects to the challenger" do
        challenger = Challenger.create! valid_attributes
        put :update, {:id => challenger.to_param, :challenger => valid_attributes}, valid_session
        response.should redirect_to(challenger)
      end
    end

    describe "with invalid params" do
      it "assigns the challenger as @challenger" do
        challenger = Challenger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Challenger.any_instance.stub(:save).and_return(false)
        put :update, {:id => challenger.to_param, :challenger => {}}, valid_session
        assigns(:challenger).should eq(challenger)
      end

      it "re-renders the 'edit' template" do
        challenger = Challenger.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Challenger.any_instance.stub(:save).and_return(false)
        put :update, {:id => challenger.to_param, :challenger => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested challenger" do
      challenger = Challenger.create! valid_attributes
      expect {
        delete :destroy, {:id => challenger.to_param}, valid_session
      }.to change(Challenger, :count).by(-1)
    end

    it "redirects to the challengers list" do
      challenger = Challenger.create! valid_attributes
      delete :destroy, {:id => challenger.to_param}, valid_session
      response.should redirect_to(challengers_url)
    end
  end

end
